POST http://localhost:8080/tasks
Content-Type: application/json

{
  "title": "Ustalenie wymaganych parametrów",
  "projectId": "1"
}


###

GET http://localhost:8080/tasks


###
GET http://localhost:8080/projects/priority

###
POST http://localhost:8080/projects?name=Zakup nowego laptopta

###
GET http://localhost:8080/projects/